User rest api
attech-org/zedb-backend pull request #1
Opened 2022-05-21 13:56 UTC by VitaliiDenysyuk

- [+ ] move env variables to .env

- [ +] implement "users" REST API

- [+ ] connect with mongodb

2022-05-21 14:34 UTC, VladislavPokhyl commented on src/db.ts
> +const MongoClient = require('mongodb').MongoClient;
It is better to use  import 'statement' then 'require'. E.g. import { MongoClient } from "mongodb";
https://flexiple.com/javascript-require-vs-import/#:~:text=One%20of%20the%20major%20differences,js%20extension%20as%20opposed%20to%20.

2022-05-21 14:36 UTC, VladislavPokhyl commented on src/repositories/user.repository.ts
> +export function getUsersData(done: any) {
For such resource-intensive processes as accessing the database, you need to use the async-await construct.

2022-05-21 16:39 UTC, VitaliiDenysyuk commented on src/db.ts
> +const MongoClient = require('mongodb').MongoClient;
> It is better to use import 'statement' then 'require'. E.g. import { MongoClient } from "mongodb"; https://flexiple.com/javascript-require-vs-import/#:~:text=One%20of%20the%20major%20differences,js%20extension%20as%20opposed%20to%20.

corrected

2022-05-21 16:41 UTC, VitaliiDenysyuk commented
corrected

2022-05-21 17:04 UTC, alexandrtovmach commented on src/app.ts
> +export var app = express();
do we need this export here?

2022-05-21 17:07 UTC, alexandrtovmach requested changes
- use mongoose instead of pure mongo client
- change flow to async/await

2022-05-21 17:07 UTC, alexandrtovmach commented on src/db.ts
> +import { MongoClient } from 'mongodb';
better to use mongoose

2022-05-21 17:07 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +    db.get().collection('users').find().toArray((err: any, docs: any) => {
don't use callbacks

2022-05-21 18:49 UTC, VitaliiDenysyuk commented on src/app.ts
> +export var app = express();
yes. We import app variable from this module in index.ts

2022-05-21 23:12 UTC, VitaliiDenysyuk commented on src/db.ts
> +import { MongoClient } from 'mongodb';
corrected

2022-05-21 23:12 UTC, VitaliiDenysyuk commented on src/repositories/user.repository.ts
> +    db.get().collection('users').find().toArray((err: any, docs: any) => {
corrected

2022-05-21 23:13 UTC, VitaliiDenysyuk commented
> * use mongoose instead of pure mongo client
> * change flow to async/await

ready

2022-05-23 16:51 UTC, alexandrtovmach commented on src/routes/users.ts
> +export const router = express.Router();
```suggestion
const router = express.Router();
```

2022-05-23 16:51 UTC, alexandrtovmach commented on src/routes/users.ts
> +
export default router;

2022-05-23 16:51 UTC, alexandrtovmach commented on src/app.ts
> +} from './routes/index';
import indexRouter from './routes/index';

2022-05-23 16:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +            });
```
const userData = await findUserByIdData(id);
if (!userData) {
    throw `Error: User by id ${id} is not found!`;
}
```

2022-05-23 16:51 UTC, alexandrtovmach commented on src/services/user.service.ts
> +        return await addUserData(user)
return addUserData(user);

2022-05-23 17:59 UTC, VitaliiDenysyuk commented
all comments are taken into account

2022-05-24 16:43 UTC, alexandrtovmach approved these changes
lgtm

2022-05-24 16:43 UTC, merged